export const assignments = [
  {
    id: 1,
    name: "Dude Ranch",
    url: `unit-1/index.html`,
    img: "img/1.png",
    discription: `Dude Ranch Assignment was a semester-start assignment. Essentially was a review assignment from what was learned in early 2021.`,
  },
  {
    id: 2,
    name: "Science Museum",
    url: `unit-2/index.html`,
    img: "unit-2/img/science-muesum-logo-quick.png",
    discription: `Science Muesum Assignment was an introduction to SCSS and I further explored SASS on my own time. The outcome of this assignment was knowledge of how to build a site using SCSS.`,
  },
  {
    id: 3,
    name: "Fruit Stand",
    url: `unit-3/index.html`,
    img: "unit-3/img/fruit-stand-logo.png",
    discription: `Fruit Stand Assignment was an assignment to practice with working images and proccessing them with Photoshop, and intoduction to lighten and darken SCSS functions.`,
  },
  {
    id: 4,
    name: "National Forest",
    url: `unit-4/index.html`,
    img: `unit-4/img/bison.png`,
    discription: `National Forest Assignment was practice to building responsive images and introduction to CSS animations.`,
  },
  {
    id: 5,
    name: "Restaurant",
    url: `unit-5/index.html`,
    img: `unit-5/img/sushi-logo-original.png`,
    discription: `Restaruant Responsive Image Assignment is a continuation of builing responsive images for websites. This assignment though implementing pixel density images that are displayed to specific devices. Outcome of this assignment was knowledge of how to provide a great image viewing experince for users.`,
  },
  {
    id: 6,
    name: "Band",
    url: `unit-6/index.html`,
    img: `unit-6/img/guitar-assignment-page.jpg`,
    discription: `Band Lazy Loading Image Assignment was building upon the last assignment, Restaurant Unit- 5. However, I've learned the basics of how to implement Lazy image loading effeciently and took the assignment further to practice with some Javascript as well.`,
  },
  {
    id: 7,
    name: "Law Firm",
    url: "unit-7/index.html",
    img: `unit-7/img/blog04.jpg`,
    discription: `Created a custom frame work with SCSS, the site has a responsive 12 grid system.`,
  },
  {
    id: 8,
    name: "News Site",
    url: "unit-8/index.html",
    img: `unit-8/img/newspaper.png`,
    discription: `This site is a test site for building a grid using CSS. I'm now able to build a site quickly wiht just CSS Grid.`,
  },
];
